# Generated by Django 5.0.6 on 2024-06-29 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_order_alter_product_image_alter_product_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Products',
        ),
    ]
